# Generated by Django 4.2.7 on 2024-01-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='quantity',
            field=models.CharField(default='1', max_length=1000),
        ),
    ]
